Repository transifex/openformats, pull requests merged in 2018-07, with the labels that each got.

#107 Handle plurals with literal values
  openformats/formats/yaml/yaml.py
  openformats/formats/yaml/yaml_i18n.py
Labels: bug

#106 Add Dockerfile and docker-compose.yml
  Makefile
  docker-compose.yml
  docker/Dockerfile
Labels: enhancement, ready

#109 Modify android escape functionality
  openformats/formats/android.py
  openformats/tests/formats/android/test_android.py
  openformats/utils/xml.py
Labels: ready
