Repository transifex/openformats, pull requests merged in 2021-08, with the labels that each got.

#225 TX-12748 pot file not uploading for dz language
  .gitignore
  openformats/formats/po.py
Labels: bug, auto-merge

#228 Release: 0.0.81
  openformats/formats/docx.py
  openformats/tests/formats/docx/files/special_cases_2.docx
  openformats/tests/formats/docx/test_docx.py
Labels: auto-merge, v:0.0.81

#230 Release: 0.0.82
  openformats/formats/docx.py
Labels: auto-merge, v:0.0.82
