Repository transifex/openformats, pull requests merged in 2021-11, with the labels that each got.

#244 Release: 0.0.87
  openformats/formats/office_open_xml/parser.py
Labels: auto-merge, v:0.0.87

#246 Release: 0.0.88
  openformats/exceptions.py
  openformats/formats/office_open_xml/parser.py
  openformats/formats/pptx.py
  openformats/tests/formats/pptx/files/autofield.pptx
  openformats/tests/formats/pptx/test_pptx.py
Labels: auto-merge, v:0.0.88

#247 Fix mapping node with anchors parsing
  openformats/formats/yaml/utils.py
  openformats/tests/formats/yamlinternationalization/files/1_el.yml
  openformats/tests/formats/yamlinternationalization/files/1_en.yml
  openformats/tests/formats/yamlinternationalization/files/1_en_exported.yml
  openformats/tests/formats/yamlinternationalization/files/1_en_exported_without_template.yml
  openformats/tests/formats/yamlinternationalization/files/1_tpl.yml
Labels: auto-merge

#251 Release: 0.0.90
  openformats/formats/json.py
  openformats/tests/formats/structuredkeyvaluejson/test_keyvaluejson.py
Labels: auto-merge, v:0.0.90

#255 Release: 0.0.91
  openformats/formats/office_open_xml/parser.py
  openformats/tests/formats/docx/files/special_cases_3.docx
  openformats/tests/formats/docx/test_docx.py
Labels: auto-merge, v:0.0.91

#258 Release: 0.0.93
  openformats/formats/json.py
  openformats/tests/formats/structuredkeyvaluejson/test_keyvaluejson.py
Labels: auto-merge, v:0.0.93

#260 Release: 0.0.94
  openformats/formats/docx.py
  openformats/tests/formats/docx/files/hello_world_no_ppr.docx
  openformats/tests/formats/docx/test_docx.py
Labels: auto-merge, v:0.0.94
