Repository transifex/openformats, pull requests merged in 2022-09, with the labels that each got.

#285 Revert skip of empty strings for json formats
  openformats/formats/json.py
Labels: bug

#286 Release: 0.0.104
  openformats/formats/json.py
Labels: auto-merge, v:0.0.104

#288 Release: 0.0.105
  requirements.txt
  setup.py
Labels: auto-merge, v:0.0.105
