Repository transifex/openformats, pull requests merged in 2023-02, with the labels that each got.

#296 Release: 0.0.107
  openformats/formats/json.py
  openformats/tests/formats/structuredkeyvaluejson/test_keyvaluejson.py
Labels: auto-merge, v:0.0.107

#294 Reimplement PO parsing to handle msgstrs with spaces
  openformats/formats/po.py
  openformats/tests/formats/po/test_po.py
Labels: enhancement

#297 Release: 0.0.108
  openformats/formats/po.py
  openformats/tests/formats/po/test_po.py
Labels: auto-merge, v:0.0.108
