Repository transifex/openformats, pull requests merged in 2023-10, with the labels that each got.

#313 Release: 0.0.113
  requirements.txt
  setup.py
Labels: auto-merge, v:0.0.113

#316 Release: 0.0.114
  requirements.txt
  setup.py
Labels: auto-merge, v:0.0.114

#317 TX-15035: Bump mistune from 0.7.3 to 0.8.1
  requirements.txt
  setup.py
Labels: dependencies

#318 Release: 0.0.115
  requirements.txt
  setup.py
Labels: auto-merge, v:0.0.115
